---
- hosts: all
  become: true
  tasks: 
  - name: get keys from vault
    debug:
      msg: "{{ lookup('hashi_vault', 'secret={{ vault_keys_path }} token={{ vault_token }} url={{ vault_server }}')}}"

- hosts: all
  become: true
  tasks: 
  - name: get ssh from vault
    debug:
      msg: "{{ lookup('hashi_vault', 'secret={{ vault_open_ssh_path }} token={{ vault_token }} url={{ vault_server }}')}}"

- hosts: all
  become: true
  tasks: 
  - name: get keys from vault
    vars:
      keys: "{{ lookup('hashi_vault', 'secret={{ vault_keys_path }} token={{ vault_token }} url={{ vault_server }}')}}"
    debug:
      msg: "user: {{ item.key }}, passwd: {{ item.value }}"
    with_items:
        - "{{ keys | dict2items }}"