--- 
- hosts: all
  become: true
  tasks: 
  - name: Get ssh from vault
    debug:
      msg: "{{ lookup('hashi_vault', 'secret={{ vault_open_ssh_path }} token={{ vault_token }} url={{ vault_server }}')}}"

- hosts: all
  become: true
  vars:
      keys: "{{ lookup('hashi_vault', 'secret={{ vault_open_ssh_path }} token={{ vault_token }} url={{ vault_server }}')}}"
  tasks: 
  - name: Check ssh key
    debug: 
      msg: "{{ item.value }}"
    with_items:
        - "{{ keys | dict2items }}"

- hosts: all
  tasks: 
  - name: Check user
    debug: 
      msg: "{{user_for_set_ssh_key}}"

- hosts: all
  become: true
  vars:
      keys: "{{ lookup('hashi_vault', 'secret={{ vault_open_ssh_path }} token={{ vault_token }} url={{ vault_server }}')}}"
  tasks: 
  - name: Set ssh key
    shell: "echo {{ item.value }} >> /home/{{user_for_set_ssh_key}}/.ssh/authorized_keys"
    with_items:
        - "{{ keys | dict2items }}"